/********************************************************************************
** Form generated from reading UI file 'keyboradl.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_KEYBORADL_H
#define UI_KEYBORADL_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>
#include <mypushbutton.h>

QT_BEGIN_NAMESPACE

class Ui_keyboradl
{
public:
    mypushbutton *pushButton_25;
    mypushbutton *pushButton_21;
    mypushbutton *pushButton_30;
    mypushbutton *pushButton_51;
    mypushbutton *pushButton_32;
    mypushbutton *pushButton_27;
    mypushbutton *pushButton_5;
    mypushbutton *pushButton_33;
    mypushbutton *pushButton;
    mypushbutton *pushButton_14;
    mypushbutton *pushButton_18;
    mypushbutton *pushButton_24;
    mypushbutton *pushButton_41;
    mypushbutton *pushButton_53;
    mypushbutton *pushButton_58;
    mypushbutton *pushButton_26;
    mypushbutton *pushButton_22;
    mypushbutton *pushButton_13;
    mypushbutton *pushButton_15;
    mypushbutton *pushButton_49;
    mypushbutton *pushButton_28;
    mypushbutton *pushButton_11;
    mypushbutton *pushButton_56;
    mypushbutton *pushButton_2;
    mypushbutton *pushButton_59;
    mypushbutton *pushButton_20;
    mypushbutton *pushButton_4;
    mypushbutton *pushButton_44;
    mypushbutton *pushButton_7;
    mypushbutton *pushButton_50;
    mypushbutton *pushButton_57;
    mypushbutton *pushButton_52;
    mypushbutton *pushButton_19;
    mypushbutton *pushButton_42;
    mypushbutton *pushButton_54;
    mypushbutton *pushButton_47;
    mypushbutton *pushButton_35;
    mypushbutton *pushButton_34;
    mypushbutton *pushButton_6;
    mypushbutton *pushButton_31;
    mypushbutton *pushButton_37;
    mypushbutton *pushButton_29;
    mypushbutton *pushButton_12;
    mypushbutton *pushButton_3;
    mypushbutton *pushButton_40;
    mypushbutton *pushButton_10;
    mypushbutton *pushButton_8;
    mypushbutton *pushButton_63;
    mypushbutton *pushButton_36;
    QTextBrowser *textBrowser;

    void setupUi(QWidget *keyboradl)
    {
        if (keyboradl->objectName().isEmpty())
            keyboradl->setObjectName(QStringLiteral("keyboradl"));
        keyboradl->resize(400, 140);
        pushButton_25 = new mypushbutton(keyboradl);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(259, 40, 25, 25));
        pushButton_25->setMinimumSize(QSize(25, 25));
        pushButton_25->setMaximumSize(QSize(25, 25));
        pushButton_25->setFocusPolicy(Qt::NoFocus);
        pushButton_21 = new mypushbutton(keyboradl);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(65, 40, 25, 25));
        pushButton_21->setMinimumSize(QSize(25, 25));
        pushButton_21->setMaximumSize(QSize(25, 25));
        pushButton_21->setFocusPolicy(Qt::NoFocus);
        pushButton_30 = new mypushbutton(keyboradl);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(176, 40, 25, 25));
        pushButton_30->setMinimumSize(QSize(25, 25));
        pushButton_30->setMaximumSize(QSize(25, 25));
        pushButton_30->setFocusPolicy(Qt::NoFocus);
        pushButton_51 = new mypushbutton(keyboradl);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(120, 71, 25, 25));
        pushButton_51->setMinimumSize(QSize(25, 25));
        pushButton_51->setMaximumSize(QSize(25, 25));
        pushButton_51->setFocusPolicy(Qt::NoFocus);
        pushButton_32 = new mypushbutton(keyboradl);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(314, 40, 25, 25));
        pushButton_32->setMinimumSize(QSize(25, 25));
        pushButton_32->setMaximumSize(QSize(25, 25));
        pushButton_32->setFocusPolicy(Qt::NoFocus);
        pushButton_27 = new mypushbutton(keyboradl);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(120, 40, 25, 25));
        pushButton_27->setMinimumSize(QSize(25, 25));
        pushButton_27->setMaximumSize(QSize(25, 25));
        pushButton_27->setFocusPolicy(Qt::NoFocus);
        pushButton_5 = new mypushbutton(keyboradl);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(176, 9, 25, 25));
        pushButton_5->setMinimumSize(QSize(25, 25));
        pushButton_5->setMaximumSize(QSize(25, 25));
        pushButton_5->setFocusPolicy(Qt::NoFocus);
        pushButton_33 = new mypushbutton(keyboradl);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(314, 71, 25, 25));
        pushButton_33->setMinimumSize(QSize(25, 25));
        pushButton_33->setMaximumSize(QSize(25, 25));
        pushButton_33->setFocusPolicy(Qt::NoFocus);
        pushButton = new mypushbutton(keyboradl);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(9, 9, 25, 25));
        pushButton->setMinimumSize(QSize(25, 25));
        pushButton->setMaximumSize(QSize(25, 25));
        pushButton->setFocusPolicy(Qt::NoFocus);
        pushButton_14 = new mypushbutton(keyboradl);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(342, 9, 50, 25));
        pushButton_14->setMinimumSize(QSize(50, 25));
        pushButton_14->setMaximumSize(QSize(50, 25));
        pushButton_14->setFocusPolicy(Qt::NoFocus);
        pushButton_18 = new mypushbutton(keyboradl);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(9, 40, 25, 25));
        pushButton_18->setMinimumSize(QSize(25, 25));
        pushButton_18->setMaximumSize(QSize(25, 25));
        pushButton_18->setFocusPolicy(Qt::NoFocus);
        pushButton_24 = new mypushbutton(keyboradl);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(287, 40, 25, 25));
        pushButton_24->setMinimumSize(QSize(25, 25));
        pushButton_24->setMaximumSize(QSize(25, 25));
        pushButton_24->setFocusPolicy(Qt::NoFocus);
        pushButton_41 = new mypushbutton(keyboradl);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(93, 102, 25, 25));
        pushButton_41->setMinimumSize(QSize(25, 25));
        pushButton_41->setMaximumSize(QSize(25, 25));
        pushButton_41->setFocusPolicy(Qt::NoFocus);
        pushButton_53 = new mypushbutton(keyboradl);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(65, 71, 25, 25));
        pushButton_53->setMinimumSize(QSize(25, 25));
        pushButton_53->setMaximumSize(QSize(25, 25));
        pushButton_53->setFocusPolicy(Qt::NoFocus);
        pushButton_58 = new mypushbutton(keyboradl);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(148, 71, 25, 25));
        pushButton_58->setMinimumSize(QSize(25, 25));
        pushButton_58->setMaximumSize(QSize(25, 25));
        pushButton_58->setFocusPolicy(Qt::NoFocus);
        pushButton_26 = new mypushbutton(keyboradl);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(93, 40, 25, 25));
        pushButton_26->setMinimumSize(QSize(25, 25));
        pushButton_26->setMaximumSize(QSize(25, 25));
        pushButton_26->setFocusPolicy(Qt::NoFocus);
        pushButton_22 = new mypushbutton(keyboradl);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(37, 40, 25, 25));
        pushButton_22->setMinimumSize(QSize(25, 25));
        pushButton_22->setMaximumSize(QSize(25, 25));
        pushButton_22->setFocusPolicy(Qt::NoFocus);
        pushButton_13 = new mypushbutton(keyboradl);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(314, 9, 25, 25));
        pushButton_13->setMinimumSize(QSize(25, 25));
        pushButton_13->setMaximumSize(QSize(25, 25));
        pushButton_13->setFocusPolicy(Qt::NoFocus);
        pushButton_15 = new mypushbutton(keyboradl);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(360, 102, 33, 25));
        pushButton_15->setMinimumSize(QSize(33, 25));
        pushButton_15->setMaximumSize(QSize(33, 25));
        pushButton_15->setFocusPolicy(Qt::NoFocus);
        pushButton_49 = new mypushbutton(keyboradl);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(37, 71, 25, 25));
        pushButton_49->setMinimumSize(QSize(25, 25));
        pushButton_49->setMaximumSize(QSize(25, 25));
        pushButton_49->setFocusPolicy(Qt::NoFocus);
        pushButton_28 = new mypushbutton(keyboradl);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(148, 40, 25, 25));
        pushButton_28->setMinimumSize(QSize(25, 25));
        pushButton_28->setMaximumSize(QSize(25, 25));
        pushButton_28->setFocusPolicy(Qt::NoFocus);
        pushButton_11 = new mypushbutton(keyboradl);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(287, 9, 25, 25));
        pushButton_11->setMinimumSize(QSize(25, 25));
        pushButton_11->setMaximumSize(QSize(25, 25));
        pushButton_11->setFocusPolicy(Qt::NoFocus);
        pushButton_56 = new mypushbutton(keyboradl);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(203, 71, 25, 25));
        pushButton_56->setMinimumSize(QSize(25, 25));
        pushButton_56->setMaximumSize(QSize(25, 25));
        pushButton_56->setFocusPolicy(Qt::NoFocus);
        pushButton_2 = new mypushbutton(keyboradl);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(37, 9, 25, 25));
        pushButton_2->setMinimumSize(QSize(25, 25));
        pushButton_2->setMaximumSize(QSize(25, 25));
        pushButton_2->setFocusPolicy(Qt::NoFocus);
        pushButton_59 = new mypushbutton(keyboradl);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(120, 102, 150, 25));
        pushButton_59->setMinimumSize(QSize(150, 25));
        pushButton_59->setMaximumSize(QSize(150, 25));
        pushButton_59->setFocusPolicy(Qt::NoFocus);
        pushButton_20 = new mypushbutton(keyboradl);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(203, 40, 25, 25));
        pushButton_20->setMinimumSize(QSize(25, 25));
        pushButton_20->setMaximumSize(QSize(25, 25));
        pushButton_20->setFocusPolicy(Qt::NoFocus);
        pushButton_4 = new mypushbutton(keyboradl);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(65, 9, 25, 25));
        pushButton_4->setMinimumSize(QSize(25, 25));
        pushButton_4->setMaximumSize(QSize(25, 25));
        pushButton_4->setFocusPolicy(Qt::NoFocus);
        pushButton_44 = new mypushbutton(keyboradl);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(9, 71, 25, 25));
        pushButton_44->setMinimumSize(QSize(25, 25));
        pushButton_44->setMaximumSize(QSize(25, 25));
        pushButton_44->setFocusPolicy(Qt::NoFocus);
        pushButton_7 = new mypushbutton(keyboradl);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(148, 9, 25, 25));
        pushButton_7->setMinimumSize(QSize(25, 25));
        pushButton_7->setMaximumSize(QSize(25, 25));
        pushButton_7->setFocusPolicy(Qt::NoFocus);
        pushButton_50 = new mypushbutton(keyboradl);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(65, 102, 25, 25));
        pushButton_50->setMinimumSize(QSize(25, 25));
        pushButton_50->setMaximumSize(QSize(25, 25));
        pushButton_50->setFocusPolicy(Qt::NoFocus);
        pushButton_57 = new mypushbutton(keyboradl);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(9, 102, 25, 25));
        pushButton_57->setMinimumSize(QSize(25, 25));
        pushButton_57->setMaximumSize(QSize(25, 25));
        pushButton_57->setFocusPolicy(Qt::NoFocus);
        pushButton_52 = new mypushbutton(keyboradl);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(300, 102, 25, 25));
        pushButton_52->setMinimumSize(QSize(25, 25));
        pushButton_52->setMaximumSize(QSize(25, 25));
        pushButton_52->setFocusPolicy(Qt::NoFocus);
        pushButton_19 = new mypushbutton(keyboradl);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(370, 45, 25, 45));
        pushButton_19->setMinimumSize(QSize(25, 45));
        pushButton_19->setMaximumSize(QSize(25, 45));
        pushButton_19->setFocusPolicy(Qt::NoFocus);
        pushButton_42 = new mypushbutton(keyboradl);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(37, 102, 25, 25));
        pushButton_42->setMinimumSize(QSize(25, 25));
        pushButton_42->setMaximumSize(QSize(25, 25));
        pushButton_42->setFocusPolicy(Qt::NoFocus);
        pushButton_54 = new mypushbutton(keyboradl);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(176, 71, 25, 25));
        pushButton_54->setMinimumSize(QSize(25, 25));
        pushButton_54->setMaximumSize(QSize(25, 25));
        pushButton_54->setFocusPolicy(Qt::NoFocus);
        pushButton_47 = new mypushbutton(keyboradl);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(93, 71, 25, 25));
        pushButton_47->setMinimumSize(QSize(25, 25));
        pushButton_47->setMaximumSize(QSize(25, 25));
        pushButton_47->setFocusPolicy(Qt::NoFocus);
        pushButton_35 = new mypushbutton(keyboradl);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(342, 40, 25, 25));
        pushButton_35->setMinimumSize(QSize(25, 25));
        pushButton_35->setMaximumSize(QSize(25, 25));
        pushButton_35->setFocusPolicy(Qt::NoFocus);
        pushButton_34 = new mypushbutton(keyboradl);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(342, 71, 25, 25));
        pushButton_34->setMinimumSize(QSize(25, 25));
        pushButton_34->setMaximumSize(QSize(25, 25));
        pushButton_34->setFocusPolicy(Qt::NoFocus);
        pushButton_6 = new mypushbutton(keyboradl);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(120, 9, 25, 25));
        pushButton_6->setMinimumSize(QSize(25, 25));
        pushButton_6->setMaximumSize(QSize(25, 25));
        pushButton_6->setFocusPolicy(Qt::NoFocus);
        pushButton_31 = new mypushbutton(keyboradl);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(287, 71, 25, 25));
        pushButton_31->setMinimumSize(QSize(25, 25));
        pushButton_31->setMaximumSize(QSize(25, 25));
        pushButton_31->setFocusPolicy(Qt::NoFocus);
        pushButton_37 = new mypushbutton(keyboradl);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(330, 102, 25, 25));
        pushButton_37->setMinimumSize(QSize(25, 25));
        pushButton_37->setMaximumSize(QSize(25, 25));
        pushButton_37->setFocusPolicy(Qt::NoFocus);
        pushButton_29 = new mypushbutton(keyboradl);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(231, 40, 25, 25));
        pushButton_29->setMinimumSize(QSize(25, 25));
        pushButton_29->setMaximumSize(QSize(25, 25));
        pushButton_29->setFocusPolicy(Qt::NoFocus);
        pushButton_12 = new mypushbutton(keyboradl);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(259, 9, 25, 25));
        pushButton_12->setMinimumSize(QSize(25, 25));
        pushButton_12->setMaximumSize(QSize(25, 25));
        pushButton_12->setFocusPolicy(Qt::NoFocus);
        pushButton_3 = new mypushbutton(keyboradl);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(93, 9, 25, 25));
        pushButton_3->setMinimumSize(QSize(25, 25));
        pushButton_3->setMaximumSize(QSize(25, 25));
        pushButton_3->setFocusPolicy(Qt::NoFocus);
        pushButton_40 = new mypushbutton(keyboradl);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(231, 71, 25, 25));
        pushButton_40->setMinimumSize(QSize(25, 25));
        pushButton_40->setMaximumSize(QSize(25, 25));
        pushButton_40->setFocusPolicy(Qt::NoFocus);
        pushButton_10 = new mypushbutton(keyboradl);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(231, 9, 25, 25));
        pushButton_10->setMinimumSize(QSize(25, 25));
        pushButton_10->setMaximumSize(QSize(25, 25));
        pushButton_10->setFocusPolicy(Qt::NoFocus);
        pushButton_8 = new mypushbutton(keyboradl);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(203, 9, 25, 25));
        pushButton_8->setMinimumSize(QSize(25, 25));
        pushButton_8->setMaximumSize(QSize(25, 25));
        pushButton_8->setFocusPolicy(Qt::NoFocus);
        pushButton_63 = new mypushbutton(keyboradl);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(259, 71, 25, 25));
        pushButton_63->setMinimumSize(QSize(25, 25));
        pushButton_63->setMaximumSize(QSize(25, 25));
        pushButton_63->setFocusPolicy(Qt::NoFocus);
        pushButton_36 = new mypushbutton(keyboradl);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(270, 102, 25, 25));
        pushButton_36->setMinimumSize(QSize(25, 25));
        pushButton_36->setMaximumSize(QSize(25, 25));
        pushButton_36->setFocusPolicy(Qt::NoFocus);
        textBrowser = new QTextBrowser(keyboradl);
        textBrowser->setObjectName(QStringLiteral("textBrowser"));
        textBrowser->setGeometry(QRect(1, 1, 399, 139));
        textBrowser->setFocusPolicy(Qt::NoFocus);
        textBrowser->setStyleSheet(QString::fromUtf8("border-image:url(:/new/prefix1/\347\256\200\347\272\246.jpg);"));
        textBrowser->raise();
        pushButton_25->raise();
        pushButton_21->raise();
        pushButton_30->raise();
        pushButton_51->raise();
        pushButton_32->raise();
        pushButton_27->raise();
        pushButton_5->raise();
        pushButton_33->raise();
        pushButton->raise();
        pushButton_14->raise();
        pushButton_18->raise();
        pushButton_24->raise();
        pushButton_41->raise();
        pushButton_53->raise();
        pushButton_58->raise();
        pushButton_26->raise();
        pushButton_22->raise();
        pushButton_13->raise();
        pushButton_15->raise();
        pushButton_49->raise();
        pushButton_28->raise();
        pushButton_11->raise();
        pushButton_56->raise();
        pushButton_2->raise();
        pushButton_59->raise();
        pushButton_20->raise();
        pushButton_4->raise();
        pushButton_44->raise();
        pushButton_7->raise();
        pushButton_50->raise();
        pushButton_57->raise();
        pushButton_52->raise();
        pushButton_19->raise();
        pushButton_42->raise();
        pushButton_54->raise();
        pushButton_47->raise();
        pushButton_35->raise();
        pushButton_34->raise();
        pushButton_6->raise();
        pushButton_31->raise();
        pushButton_37->raise();
        pushButton_29->raise();
        pushButton_12->raise();
        pushButton_3->raise();
        pushButton_40->raise();
        pushButton_10->raise();
        pushButton_8->raise();
        pushButton_63->raise();
        pushButton_36->raise();

        retranslateUi(keyboradl);

        QMetaObject::connectSlotsByName(keyboradl);
    } // setupUi

    void retranslateUi(QWidget *keyboradl)
    {
        keyboradl->setWindowTitle(QApplication::translate("keyboradl", "Form", 0));
        pushButton_25->setText(QApplication::translate("keyboradl", "P", 0));
        pushButton_21->setText(QApplication::translate("keyboradl", "E", 0));
        pushButton_30->setText(QApplication::translate("keyboradl", "U", 0));
        pushButton_51->setText(QApplication::translate("keyboradl", "F", 0));
        pushButton_32->setText(QApplication::translate("keyboradl", "*", 0));
        pushButton_27->setText(QApplication::translate("keyboradl", "T", 0));
        pushButton_5->setText(QApplication::translate("keyboradl", "7", 0));
        pushButton_33->setText(QApplication::translate("keyboradl", "\343\200\202", 0));
        pushButton->setText(QApplication::translate("keyboradl", "1", 0));
        pushButton_14->setText(QApplication::translate("keyboradl", "Backspace", 0));
        pushButton_18->setText(QApplication::translate("keyboradl", "Q", 0));
        pushButton_24->setText(QApplication::translate("keyboradl", "/", 0));
        pushButton_41->setText(QApplication::translate("keyboradl", "V", 0));
        pushButton_53->setText(QApplication::translate("keyboradl", "S", 0));
        pushButton_58->setText(QApplication::translate("keyboradl", "G", 0));
        pushButton_26->setText(QApplication::translate("keyboradl", "R", 0));
        pushButton_22->setText(QApplication::translate("keyboradl", "W", 0));
        pushButton_13->setText(QApplication::translate("keyboradl", "+", 0));
        pushButton_15->setText(QApplication::translate("keyboradl", "<-", 0));
        pushButton_49->setText(QApplication::translate("keyboradl", "A", 0));
        pushButton_28->setText(QApplication::translate("keyboradl", "Y", 0));
        pushButton_11->setText(QApplication::translate("keyboradl", "-", 0));
        pushButton_56->setText(QApplication::translate("keyboradl", "J", 0));
        pushButton_2->setText(QApplication::translate("keyboradl", "2", 0));
        pushButton_59->setText(QApplication::translate("keyboradl", "space", 0));
        pushButton_20->setText(QApplication::translate("keyboradl", "I", 0));
        pushButton_4->setText(QApplication::translate("keyboradl", "3", 0));
        pushButton_44->setText(QApplication::translate("keyboradl", "Cap", 0));
        pushButton_7->setText(QApplication::translate("keyboradl", "6", 0));
        pushButton_50->setText(QApplication::translate("keyboradl", "C", 0));
        pushButton_57->setText(QApplication::translate("keyboradl", "Z", 0));
        pushButton_52->setText(QApplication::translate("keyboradl", "N", 0));
        pushButton_19->setText(QApplication::translate("keyboradl", "Ent", 0));
        pushButton_42->setText(QApplication::translate("keyboradl", "X", 0));
        pushButton_54->setText(QApplication::translate("keyboradl", "H", 0));
        pushButton_47->setText(QApplication::translate("keyboradl", "D", 0));
        pushButton_35->setText(QApplication::translate("keyboradl", "\343\200\201", 0));
        pushButton_34->setText(QApplication::translate("keyboradl", "?", 0));
        pushButton_6->setText(QApplication::translate("keyboradl", "5", 0));
        pushButton_31->setText(QApplication::translate("keyboradl", ",", 0));
        pushButton_37->setText(QApplication::translate("keyboradl", "M", 0));
        pushButton_29->setText(QApplication::translate("keyboradl", "O", 0));
        pushButton_12->setText(QApplication::translate("keyboradl", "0", 0));
        pushButton_3->setText(QApplication::translate("keyboradl", "4", 0));
        pushButton_40->setText(QApplication::translate("keyboradl", "K", 0));
        pushButton_10->setText(QApplication::translate("keyboradl", "9", 0));
        pushButton_8->setText(QApplication::translate("keyboradl", "8", 0));
        pushButton_63->setText(QApplication::translate("keyboradl", "L", 0));
        pushButton_36->setText(QApplication::translate("keyboradl", "B", 0));
    } // retranslateUi

};

namespace Ui {
    class keyboradl: public Ui_keyboradl {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_KEYBORADL_H
